Fixed a small bug related to multi-constrain k-way partitioning
TUM-I5/PUML2 pull request #3
Opened 2021-10-11 15:46 UTC by ravil-mobile

* added an option for a user to pass a vector of imbalances
* the current SeisSol's master branch references this branch

2021-10-12 13:30 UTC, krenzland requested changes
Looks mostly good, just one tiny change.

2021-10-12 13:30 UTC, krenzland commented on PartitionMetis.h
> +	enum Status {
should be enum class

2022-07-05 07:55 UTC, Thomas-Ulrich approved these changes

2022-07-05 08:01 UTC, krenzland commented
@ravil-mobile Is this PR still relevant?

2022-07-05 08:04 UTC, Thomas-Ulrich commented
I think it is (see other PR, extending this PR, required for Edgeweigts constraints).

2022-07-06 09:01 UTC, ravil-mobile commented on PartitionMetis.h
> +	enum Status {
done

2022-07-06 10:16 UTC, krenzland approved these changes

2022-07-06 10:16 UTC, merged