Fix HDF5 errors with large number of ranks
TUM-I5/PUML2 pull request #6
Opened 2022-10-28 16:01 UTC by sebwolf-de

When using a lot of ranks, we obtained some HDF5 errors, see e.g. https://github.com/SeisSol/SeisSol/issues/718
This pull request fixes that issue, by introducing a new vertex distribution:
If we have `V` vertices and `R` ranks, the first `V%R` ranks will read `V/R + 1` elements and the remaining ranks will read `V/R` ranks. 
Todo: Consider the same distribution for the element array.

2022-11-02 16:29 UTC, sebwolf-de commented
Test setup:
SeisSol with this branch as submodule vs SeisSol with current master as submodule, Scenario: small ridgecrest mesh with `2335541 cells, 420823 vertices`. 

1.) Let both SeisSol versions run with 100 ranks: Solutions coincide after 2s.
2.) Run both SeisSol versions on 1152 ranks 
* Old version (96 nodes, 12 ranks/node) runs into the problem https://github.com/SeisSol/SeisSol/issues/718
* New version (576 nodes, 2 ranks/node) doesn't run into the problem, solution after 2s coincides with the other runs from 1).

2022-11-03 10:32 UTC, krenzland requested changes
Thanks, looks very clean. Just a few suggestions regarding the init() pattern

2022-11-03 10:32 UTC, krenzland commented on PUML.h
> +    missingEntities = numEntities % numRanks;
Why is this not in the constructor?
The construcor + init() pattern is very common in our codebase but is actually not a great design..

2022-11-03 10:32 UTC, krenzland commented on PUML.h
> +  unsigned long missingEntities;
This should all be const imo

2022-11-03 10:32 UTC, krenzland commented on PUML.h
> +    missingEntities = numEntities % numRanks;
If you wouldn't use it, everything here could be const

2022-11-03 10:32 UTC, krenzland commented on PUML.h
> +    missingEntities = numEntities % numRanks;
I've checked below, it can be changed!

2022-11-03 10:32 UTC, krenzland commented on PUML.h
> +	Distributor m_vertexDistributor;
Need not be class member

2022-11-03 14:09 UTC, krenzland approved these changes

2022-11-03 14:09 UTC, merged